[env:esp32-c3-devkitm-1]
platform      = espressif32
board         = esp32-c3-devkitm-1
framework     = arduino
monitor_speed = 115200

lib_deps =
    Chris--A/Keypad@^3.1.1
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    bblanchon/ArduinoJson@^7.0.0

; Retirer pour le vrai ESP32 physique
build_flags = -DWOKWI_SIM=1
